const required = require("../middlewares/utility/required");

module.exports = {
  users: {
    register: require("./users/register"),
    login: require("./users/login"),
    wallet: require("./users/createWallet"),
    attemptUnlock: require("./users/attemptUnlock"),
    buy: require("./users/buyTokens"),
    transfer: require("./users/transferToken"),
    claim: require("./users/claimToken.js"),
    unstake: require("./users/unstakeToken.js"),
    issue: require("./users/issueTokens"),
    totalSupply: require("./users/totalSupply"),
    transferFee: require("./users/transferFees"),
    burn: require("./users/burnToken"),
    vesting1: require("./users/vestingV1"),
    vesting2: require("./users/vestingV2"),
    getVestingV1: require("./users/getVestingV1"),
    getVestingV2: require("./users/getVestingV2"),
    lockedVestingInfo: require("./users/lockedVestingInfo"),
    queryWallet: require("./users/queryWallet"),
    queryWalletAdmin: require("./users/queryWalletAdmin"),
    fetchWallets: require("./users/wallets"),
    defaultWallets: require("./users/getDefaultWallets"),
    transactions: require("./users/transactions"),
    issuedTokens: require("./users/issuedTokens"),
    stakingInfo: require("./users/stakingInfo"),
    recoverUser: require("./users/recoverUser"),
    resetPassword: require("./users/resetPassword"),
    addAdmin: require("./users/addAdmin"),
    userWallets: require("./users/userWallets"),
    sendMessage: require("./users/sendMessage"),
    sendMessageTransactions: require("./users/sendMessageTransactions"),
    createPool: require("./users/createPool"),
    createVote: require("./users/createVote"),
    destroyPool: require("./users/destroyPool"),
    queryPool: require("./users/queryPool"),
    poolHistory: require("./users/poolHistory"),
    getCurrentPhase: require("./users/getCurrentPhase"),
    getCurrentFee: require("./users/getFee"),
    getPoolConfig: require("./users/poolConfig"),
    updatePoolConfig: require("./users/updatePoolConfig"),
    updateBlocks: require("./users/updateBlocks"),
    getBlocks: require("./users/getBlocks"),
    stakingTransactions: require("./users/stakingTransactions"),
    claimTransactions: require("./users/claimTransactions"),
    unstakeTransactions: require("./users/unstakeTransactions"),
  },

  auth: {
    generateToken: require("./auth/generate-token"),
    generateTokenAdmin: require("./auth/generate-token-admin"),
    apiKey: require("./auth/apiKey"),
  },
};
