version: '2.1'

networks:
  busy-blockchain:

services:
  couchdb.peer0.busy.technology:
    container_name: couchdb.peer0.busy.technology
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=****
      - COUCHDB_PASSWORD=******
    ports:
      - "5984:5984"
    networks:
      - busy-blockchain

  peer0.busy.technology:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.busy.technology:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=*****
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=*******
    depends_on:
      - couchdb.peer0.busy.technology

  couchdb.peer1.busy.technology:
    container_name: couchdb.peer1.busy.technology
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=*****
      - COUCHDB_PASSWORD=*****
    ports:
      - "6984:5984"
    networks:
      - busy-blockchain

  peer1.busy.technology:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.busy.technology:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=*****
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=*******
    depends_on:
      - couchdb.peer1.busy.technology

    
